### ISSUE TITLE
Automated Testing Checklist

### ISSUE THREAD

**Issue by JWhitleyAStuff** [astuff/kvaser_interface#34]
This is to discuss the addition of automated unit and node tests and what tests make sense to complete. The tests below assume that 2 virtual CAN channels have been created. After some discussion with @zoakesAStuff, this is an initial pass:

### Unit Tests (for `kvaser_interface`) - Implemented in #37 ###

- [x] KvaserCan::open() while channel is closed. Expected output: ReturnStatuses::OK
- [x] KvaserCan::open() while channel is open. Expected output: ReturnStatuses::OK
- [x] KvaserCan::close() while channel is closed. Expected output: ReturnStatuses::CHANNEL_CLOSED
- [x] KvaserCan::close() while channel is open. Expected output: ReturnStatuses::OK
- [x] KvaserCan::isOpen() while channel is closed. Expected output: false
- [x] KvaserCan::isOpen() while channel is open. Expected output: true
- [x] KvaserCan::read() while channel is closed. Expected output: ReturnStatuses::CHANNEL_CLOSED
- [x] KvaserCan::read() while channel is open and no messages are being transmitted. Expected output: ReturnStatuses::NO_MESSAGES_RECEIVED
- [x] KvaserCan::read() while channel is open and messages are being transmitted. Expected output: ReturnStatuses::OK
- [x] KvaserCan::registerReadCallback() while channel is closed. Expected output: ReturnStatuses::CHANNEL_CLOSED
- [x] KvaserCan::registerReadCallback() while channel is open. Expected output: ReturnStatuses::OK
- [x] Read Callback Function after registering callback while channel is open and message is transmitted. Expected output: callback is called.
- [x] KvaserCan::write() while channel is closed. Expected output: ReturnStatuses::CHANNEL_CLOSED
- [x] KvaserCan::write() while channel is open. Expected output: ReturnStatuses::OK
- [x] KvaserCanUtils::dlcToSize() Expected output: Correct size values, 0 if invalid.
- [x] KvaserCanUtils::sizeToDlc() Expected output: Correct DLC values, 0 if invalid.
- [x] KvaserCanUtils::getChannelCount() Expected output: 2 (see note above)
- [x] KvaserCanUtils::getCards() Expected output: 1 (see note above)
- [x] KvaserCanUtils::getChannels() Expected output: a std::vector of 2 channels (see note above)
- [x] KvaserCanUtils::getChannelsOnCard() Expected output: a std::vector of 2 channels (see note above)
- [x] Sent a message on channel 1 with KvaserCan::write() and listen on channel 1 with KvaserCan::read(). Expected output: Message contents written and read are identical.
    - [x] Above test with DLC == 0. Expected output: ReturnStatuses::OK
    - [x] Above test with standard message ID and DLC != payload size. Expected output: Write failure.
    - [x] Above test with ID > 2^11 and is_extended flag == false. Expected output: Write failure.
    - [x] Above test with ID <= 2^11 and is_extended flag == true. Expected output: ReturnStatuses::OK (standard IDs are still valid when Extended IDs are allowed).
- [x] KvaserCanUtils::getMsgFromFlags() Set flags to 0xFFFFFFFF. Expected output: All flags in the message will be set to true.
- [x] KvaserCanUtils::getMsgFromFlags() Set flags to 0x000000000. Expected output: All flags in the message will be set to false.
- [x] KvaserCanUtils::getFlagsFromMsg() Set all flags in message to true. Expected output: All bits associated with known flags will be set to 1.
- [x] KvaserCanUtils::getFlagsFromMsg() Set all flags in message to false. Expected output: Flags will be 0x00000000.

### Node Tests (for `kvaser_can_bridge`) - Implemented in #40 ###

These tests assume that the virtual channels (2) are still available. The testing rig would set up 2 instances of `kvaser_can_bridge`: One connected to channel 1 (writer) and one connected to channel 2 (reader).

- [x] Write to /writer/can_rx at 100Hz. Expected output: messages produced on /reader/can_tx at 100Hz (+- 3.0Hz)
- [x] Write to /writer/can_rx. Expected output: message produced on /reader/can_tx with contents identical to written message.
    - [x] Above test with DLC == 0. Expected output: Received message is identical to sent message except payload is all 0s.
    - [x] Above test with standard message ID and DLC != payload size. Expected output: Received message is identical to sent message except payload is only populated up to DLC value.
    - [x] Above test with ID > 2^11 and is_extended flag == false. Expected output: Write failure - no matching message received.
    - [x] Above test with ID <= 2^11 and is_extended flag == true. Expected output: Write failure - no matching message received.

**Comment by zoakesAStuff** [comment]
Some more Node Tests that I think might be valuable: 

- [ ] Send message with DLC 0 Expected output: Message received with empty payload
- [ ] Send message with data.size != dlc Expected output ?? 
- [ ] Send message with ID > 2^11 and is_extended flag not set  Expected output: ???
 - [] Send message with ID < 2^11 and is_extended flag set  Expected output: Message as normal, left zero padded ID

**Comment by zoakesAStuff** [comment]
- [ ] With both nodes connected, write to /writer/can_rx  Expected output: Identical message published on /reader/can_tx

**Comment by JWhitleyAStuff** [comment]
> * [ ]  With both nodes connected, write to /writer/can_rx  Expected output: Identical message published on /reader/can_tx

I added this one at the bottom: 

- [ ] Write to /writer/can_rx. Expected output: message produced on /reader/can_tx with contents identical to written message.

**Comment by JWhitleyAStuff** [comment]
> Some more Node Tests that I think might be valuable:
> 
> * [ ]  Send message with DLC 0 Expected output: Message received with empty payload
> * [ ]  Send message with data.size != dlc Expected output ??
> * [ ]  Send message with ID > 2^11 and is_extended flag not set  Expected output: ???
> * [ ]  Send message with ID < 2^11 and is_extended flag set  Expected output: Message as normal, left zero padded ID

I added these with one change: The last item causes a write failure at the Kvaser canlib level so I would expect it to do the same in `kvaser_interface`.
